"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { motion, useMotionValue, useTransform, type MotionValue } from "framer-motion";
import { RECOVERY_FEATURES } from "@/lib/constants";
import { useReducedMotion } from "@/lib/useReducedMotion";
import { useHasMounted } from "@/lib/useHasMounted";
import desktopManifest from "@/public/hero/desktop/manifest.json";
import mobileManifest from "@/public/hero/mobile/manifest.json";
import "./equipment-hero-section.css";

/** The hero renders the same eight seconds of footage two different ways.
 *
 * Desktop (HeroScrub) scrubs a frame sequence against scroll: the athlete
 * only moves when the page does, and stops dead on a measured pose while
 * each beat's copy is read. That is the whole point of it there — a big
 * screen has the scroll distance to spend and a pointer precise enough to
 * make the scrubbing feel like direct manipulation.
 *
 * Mobile (HeroLoop) plays public/videos/hero-loop.mp4 on a loop instead,
 * with the copy cued off the video's own clock. A phone gets the hero as a
 * moving image it can simply watch rather than one it has to operate, and
 * the page above it is an ordinary 100vh section again — no multi-viewport
 * scroll container, no frame decoding, no per-tick canvas blit. Video
 * playback is the one thing a phone's media pipeline does in dedicated
 * hardware, entirely off the main thread.
 *
 * Both readings share this file's geometry, its copy, and the chapter
 * anchors in the manifests — the same measured poses either hold the scrub
 * still or cue a line of type, so the two never tell different stories.
 *
 * The frame sets themselves are generated by scripts/encode-hero-frames.mjs
 * from the PNG masters in public/athlete/ — see that file for why the
 * masters can't be served directly, and for the more important reason it
 * runs an analysis pass: 61% of the masters are exact duplicates of the
 * frame before them, and scrubbing that judder is what used to read as
 * scroll lag. */
type Chapter = {
  key: string;
  /** The moment this pose arrives, as a fraction of the source clip, 0..1 —
   * what the mobile video loop cues its copy off. Both manifests carry it,
   * which is what keeps the two renderings telling the same story. */
  at: number;
};

/** A chapter in a variant that publishes a frame sequence: `frame` is the
 * index in it that the scrub holds still on. */
type ScrubChapter = Chapter & { frame: number };

type FrameSet = {
  dir: string;
  count: number;
  width: number;
  height: number;
  /** Fraction of the frame's height where his feet meet the floor. */
  groundY: number;
  /** The poses the hero stops on, one per beat. */
  chapters: readonly ScrubChapter[];
  /** Device-pixel-ratio ceiling for the drawing buffer. */
  maxDpr: number;
};

/** The set the desktop scrub draws. */
const DESKTOP: FrameSet = { dir: "/hero/desktop", ...desktopManifest, maxDpr: 2 };

/** Mobile publishes no sequence — the video is the moving image. What its
 * manifest still carries is the geometry the stylesheet builds around that
 * video (the crop window the athlete was measured into, the ground line,
 * the backdrop colours), the clip positions its copy is cued from, and one
 * poster frame to hold under the video until it starts — and on iOS Low
 * Power Mode, which refuses inline autoplay, instead of it. */
const MOBILE = { ...mobileManifest, posterSrc: `/hero/mobile/${mobileManifest.poster}` };

const HERO_VIDEO = "/videos/hero-loop.mp4";

type Variant = "desktop" | "mobile";

const framePath = (dir: string, i: number) =>
  `${dir}/${String(i).padStart(4, "0")}.webp`;

/** Fallback fill behind a desktop frame — matches the athlete sequence's
 * solid red backdrop. With IMAGE_SCALE=1 (true cover) this is only ever
 * visible for a sub-pixel rounding edge. Mobile never uses it: it fills
 * from the per-frame sampled colours in the manifest instead. */
const BACKDROP_FALLBACK = "#c21300";

const IMAGE_SCALE = 1;
// Matches the .hero-canvas media query breakpoint (max-width: 768px) in
// equipment-hero-section.css.
const MOBILE_BREAKPOINT = 768;

/** The mobile diagonal, as fractions of viewport height where the split
 * meets the left and right edges of the screen. Everything above it is
 * clipped off the canvas, exposing the container's midnight background, so
 * the hero reads as a black field over a red one — the portrait answer to
 * the desktop wedge. These are handed to the stylesheet as custom
 * properties on .hero-container (see the render below) rather than written
 * twice, because MOBILE_MAX_HEIGHT below is derived from them. */
const MOBILE_DIAGONAL_LEFT = 0.62;
const MOBILE_DIAGONAL_RIGHT = 0.28;

/** Where the athlete's feet land, as a fraction of viewport height, and the
 * most of the viewport height his band may occupy. Anchoring to his feet
 * rather than centring the band keeps him standing at the same height on
 * screen across every viewport, and keeps the floor line stable while his
 * pose changes underneath it.
 *
 * MOBILE_MAX_HEIGHT is not a round number: it is the largest cap that keeps
 * every frame's silhouette clear of the diagonal above. The band is sized
 * off the canvas *width*, while the diagonal is placed off its *height*, so
 * on a short wide viewport he grows relative to the split and his head
 * crosses it — at the old 0.92 he was cut on every 16:9 phone. Capping the
 * band against viewport height instead shrinks him there (the backdrop fill
 * takes the spare width) and leaves modern ~19.5:9 phones, where width
 * still binds, untouched.
 *
 * Verify with `node scripts/verify-hero-diagonal.mjs` after changing any of
 * these, the diagonal, or the crop — it measures the published frames. */
const MOBILE_FEET_Y = 0.88;
const MOBILE_MAX_HEIGHT = 0.425;

// Horizontal anchor for drawImage's cover-fit crop: 0 = left edge of the
// frame shown, 0.5 = centered, 1 = right edge. The canvas is confined to a
// right-hand column (see the media query on .hero-canvas), so this only
// needs to add a small further nudge, drifted toward as the user scrolls so
// the athlete visibly settles rightward rather than sitting static.
const ANCHOR_BASE = 0.5;
const ANCHOR_MAX = 0.64;
const ANCHOR_SCROLL_WINDOW = 0.06;

function computeAnchorX(progress: number) {
  const t = Math.max(0, Math.min(1, progress / ANCHOR_SCROLL_WINDOW));
  return ANCHOR_BASE + (ANCHOR_MAX - ANCHOR_BASE) * t;
}

/** How many frames may be in flight at once behind the anchors. The
 * original code queued every remaining frame in a single synchronous loop,
 * which meant hundreds of simultaneous requests contending with each other
 * and with the fonts and the rest of the page. */
const LOAD_CONCURRENCY = 6;

// ---------------------------------------------------------------------------
// Scroll timeline
// ---------------------------------------------------------------------------

/** Share of the hero's scroll each chapter spends *held* on its anchor
 * frame, and the share at the end reserved for the fade to black.
 *
 * The holds are the whole point of the rebuild. A linear progress -> frame
 * map never rests on anything: every pose is a frame you are already
 * scrolling away from, so the athlete is permanently a blur in transit and
 * the copy has to be read off a moving background. Stopping him on a
 * measured, sharp frame (see CHAPTERS in scripts/encode-hero-frames.mjs)
 * for a tenth of the hero turns each beat into a held photograph with a
 * line of type beside it, which is the thing that reads as deliberate
 * rather than laggy.
 *
 * Four beats at 0.10 plus the short opening hold below leaves 0.50 for
 * travel. Against the 520vh of scroll range the stylesheet gives the hero
 * that is ~52vh of stillness per beat and ~1.1vh of scroll per frame while
 * he moves — close to the pacing the old linear map had, except now every
 * one of those frames differs from the one before it.
 *
 * Check both with `npm run hero:timeline`, which prints the timeline these
 * produce and fails if the holds collide or his playback rate lurches. */
const DWELL = 0.1;
const OUTRO = 0.07;

/** The opening chapter gets a much shorter hold than the rest, because its
 * hold has mostly already happened: the h1 over the stance frame is what is
 * on screen before a single pixel of scroll, so the reader has had as long
 * as they wanted with it. Giving it a full DWELL would spend the first 52vh
 * of scrolling with the frame held and the h1 pinned — the user drags, and
 * nothing whatsoever moves, which is exactly the "is this broken?" feeling
 * the rest of this work is trying to remove. 0.03 is a short settle so the
 * very first scroll does not jerk straight into motion. */
const INTRO_DWELL = 0.03;

const dwellFor = (i: number) => (i === 0 ? INTRO_DWELL : DWELL);

type Segment = { frame: number; holdStart: number; holdEnd: number };

/** Lays the chapters out along scroll progress, giving each *travel* stretch
 * a share of the leftover scroll proportional to how many frames it has to
 * cross.
 *
 * Proportional rather than equal because the anchors are not evenly spaced
 * in the footage — stance to guard is 81 frames, guard to drive is 27. Equal
 * scroll per gap would play the first stretch at three times the speed of
 * the second, so his apparent playback rate would lurch every time a beat
 * ended. Sharing the budget by frame count instead keeps one constant
 * frames-per-pixel across the whole hero, and derives it from the manifest,
 * so re-encoding the footage re-times the hero rather than silently
 * desyncing it. */
function buildTimeline(chapters: readonly ScrubChapter[]): Segment[] {
  const gaps = chapters
    .slice(1)
    .map((c, i) => Math.max(1, c.frame - chapters[i].frame));
  const totalGap = gaps.reduce((a, b) => a + b, 0);
  const totalDwell = chapters.reduce((sum, _, i) => sum + dwellFor(i), 0);
  const travelBudget = Math.max(0, 1 - OUTRO - totalDwell);

  const segments: Segment[] = [];
  let t = 0;
  chapters.forEach((c, i) => {
    segments.push({ frame: c.frame, holdStart: t, holdEnd: t + dwellFor(i) });
    t += dwellFor(i);
    if (i < gaps.length) t += (travelBudget * gaps[i]) / totalGap;
  });
  return segments;
}

/** Ease with zero slope at both ends, so he decelerates into a pose and
 * accelerates out of it instead of stopping dead and restarting. A hard
 * stop at the hold boundary is what makes a scrub feel broken — the motion
 * has to arrive at rest, not be switched off. */
const smoothstep = (u: number) => u * u * (3 - 2 * u);

/** Scroll progress -> frame index, holding still across each chapter's
 * dwell window and easing between them. */
function frameAtProgress(segments: Segment[], p: number) {
  if (p <= segments[0].holdEnd) return segments[0].frame;
  for (let i = 0; i < segments.length - 1; i++) {
    const a = segments[i];
    const b = segments[i + 1];
    if (p < b.holdStart) {
      const u = (p - a.holdEnd) / (b.holdStart - a.holdEnd);
      return a.frame + (b.frame - a.frame) * smoothstep(u);
    }
    if (p <= b.holdEnd) return b.frame;
  }
  return segments[segments.length - 1].frame;
}

/** The chapter whose hold `p` currently falls in, or is nearest to — used
 * only under reduced motion, where the frame snaps between anchors instead
 * of scrubbing. */
function chapterAtProgress(segments: Segment[], p: number) {
  let best = 0;
  for (let i = 1; i < segments.length; i++) {
    if (p >= segments[i].holdStart - DWELL / 2) best = i;
  }
  return best;
}

// ---------------------------------------------------------------------------
// Loop timeline (mobile)
// ---------------------------------------------------------------------------

/** How fast the clip plays, and how the copy is paced against it.
 *
 * The clip is eight seconds long. Five beats cannot be read in eight
 * seconds — cueing each one to the moment its own pose arrives gives the
 * last of them 0.6s on screen at this rate — so the two are on different
 * cycles: the video loops every clip, and the copy advances one beat per
 * loop. A beat therefore holds for a whole pass of the footage, about six
 * and a half seconds, and the full set of five takes five passes.
 *
 * The trade that buys is worth naming, because an earlier version of this
 * made the opposite one: the copy no longer describes the pose on screen at
 * that instant. It cannot, at a playback rate where the athlete runs his
 * whole routine in the time it takes to read one line. His pose does come
 * round inside the pass its beat is on (the manifest's `at` says where), but
 * the beat is ambient over the loop rather than locked to a frame. The
 * desktop scrub still locks exactly — there, the reader controls the clock.
 *
 * The advance lands on the loop's own restart, so the copy changes in the
 * same instant the footage cuts back to the opening stance. That reads as
 * one deliberate chapter change instead of two unrelated jumps, and it is
 * the reason the phase below is counted off the video rather than a timer. */
const LOOP_RATE = 1.25;
/** Crossfade half-width, as a share of the whole five-pass cycle. */
const LOOP_FADE = 0.01;

type LoopWindow = { from: number; to: number };

/** One window per chapter, each an equal share of the cycle — which is one
 * pass of the video, since the cycle is exactly as many passes as there are
 * chapters. Expressed as a list rather than derived from an index at the
 * call site so the loop and the scrub keep the same shape, and so
 * `npm run hero:timeline` can print and check it. */
function buildLoopWindows(chapters: readonly Chapter[]): LoopWindow[] {
  return chapters.map((_, i) => ({ from: i / chapters.length, to: (i + 1) / chapters.length }));
}

// ---------------------------------------------------------------------------
// Copy
// ---------------------------------------------------------------------------

/** One beat per chapter the athlete actually holds a pose for, joined to
 * the frames by `key` (the anchors themselves live in
 * scripts/encode-hero-frames.mjs, next to the footage analysis that picks
 * them). The pose is the constraint, not the discipline list: the footage
 * has four distinct actions after the opening stance, so the disciplines
 * are grouped onto the shape the athlete is genuinely making rather than
 * split one-per-beat and forced to reuse poses.
 *
 * `stance` has no entry — its chapter is the h1 in .hero-content, which
 * takes the same slot in both timelines and is styled the same way.
 *
 * `heading` must contain `accent` verbatim once — the render below splits
 * on it to color that one word, the same "single accent word" rule
 * .hero-headline follows for "Limit". */
const BEATS: Array<{
  key: string;
  index: string;
  label: string;
  heading: string;
  accent: string;
  body: string;
}> = [
  {
    key: "guard",
    index: "01",
    label: "Strike",
    heading: "Learn To Fight.",
    accent: "Fight",
    body: "Boxing. MMA. Grappling. Coached from first stance to sparring.",
  },
  {
    key: "drive",
    index: "02",
    label: "Push",
    heading: "Built For Hyrox.",
    accent: "Hyrox",
    body: "HYROX, functional conditioning and high-intensity training under one roof.",
  },
  {
    key: "floor",
    index: "03",
    label: "Own It",
    heading: "Own Your Bodyweight.",
    accent: "Bodyweight",
    body: "CrossFit and calisthenics — strength, skill and control, no machine required.",
  },
  {
    key: "recover",
    index: "04",
    label: "Recover",
    heading: "Recover Like A Pro.",
    accent: "Pro",
    body: RECOVERY_FEATURES.map((f) => f.title).join(". ") + ".",
  },
];

/** The inside of one beat, identical in both renderings — only what drives
 * its opacity differs (a scrollbar on desktop, the video's clock on
 * mobile). */
function BeatCopy({ beat }: { beat: (typeof BEATS)[number] }) {
  return (
    <>
      <span className="section-label font-display">
        {beat.index} / {beat.label}
      </span>
      <h2 className="beat-heading font-display">
        {beat.heading.split(beat.accent).map((part, j, parts) => (
          <span key={j}>
            {part}
            {j < parts.length - 1 && <span className="hero-headline-accent">{beat.accent}</span>}
          </span>
        ))}
      </h2>
      <p className="beat-body">{beat.body}</p>
    </>
  );
}

/** The h1, in both renderings. `entered` gates the mount animation: Framer
 * Motion server-renders using the `animate` values, not `initial` (so
 * no-JS/slow-hydration users see the correct final layout rather than
 * hidden/offset text) — then, on hydrate, if the DOM already matches
 * `animate`, it skips the enter transition entirely. That made every slide
 * here a no-op. Gating `animate` on a flip that only happens client-side,
 * after mount, forces a genuine post-mount prop change, which Framer Motion
 * always animates regardless of what SSR produced. */
function HeroHeadline({ entered, reducedMotion }: { entered: boolean; reducedMotion: boolean }) {
  const ease = [0.22, 1, 0.36, 1] as const;
  const duration = reducedMotion ? 0 : 0.9;
  return (
    <h1 className="hero-headline">
      <motion.span
        style={{ display: "inline-block", marginRight: "0.28em" }}
        initial={{ opacity: 0, x: -80 }}
        animate={entered ? { opacity: 1, x: 0 } : { opacity: 0, x: -80 }}
        transition={{ duration, ease, delay: reducedMotion ? 0 : 0.15 }}
      >
        Your
      </motion.span>
      <motion.span
        className="hero-headline-accent"
        style={{ display: "inline-block", marginRight: "0.28em" }}
        initial={{ opacity: 0, x: 80 }}
        animate={entered ? { opacity: 1, x: 0 } : { opacity: 0, x: 80 }}
        transition={{ duration, ease, delay: reducedMotion ? 0 : 0.3 }}
      >
        Limit
      </motion.span>
      <motion.span
        style={{ display: "inline-block" }}
        initial={{ opacity: 0, y: 24 }}
        animate={entered ? { opacity: 1, y: 0 } : { opacity: 0, y: 24 }}
        transition={{ duration, ease, delay: reducedMotion ? 0 : 0.45 }}
      >
        Is You.
      </motion.span>
    </h1>
  );
}

/** Opacity and lift for one beat, windowed on that chapter's hold.
 *
 * The copy resolves while he is decelerating into the pose and is fully up
 * for essentially the whole hold, so the reading happens against a still
 * image rather than a moving one — the sequencing the beats were always
 * meant to have and never got from a window defined in raw scroll
 * fractions.
 *
 * No animated `filter: blur()` any more. It was the single most expensive
 * thing in the hero: three fixed inset:0 layers each re-rasterising a
 * full-viewport blur on every scroll tick, on top of the canvas blit. It
 * also produced the smeared mid-transition text that made the hero look
 * like it was failing to keep up — the blur *was* the lag people were
 * seeing. A short lift and a crossfade give the same softness for the cost
 * of two compositor properties. */
function useBeatMotion(
  progress: MotionValue<number>,
  segment: Segment,
  reducedMotion: boolean,
) {
  const lead = 0.035;
  const tail = 0.03;
  const opacity = useTransform(
    progress,
    [segment.holdStart - lead, segment.holdStart + 0.012, segment.holdEnd - 0.012, segment.holdEnd + tail],
    [0, 1, 1, 0],
  );
  const rawY = useTransform(progress, [segment.holdStart - lead, segment.holdStart + 0.012], [34, 0]);
  const y = useTransform(rawY, (v) => (reducedMotion ? 0 : v));
  // Only the beat that is actually on screen keeps a composited layer.
  // Four fixed, full-viewport layers stacked over the canvas cost real
  // memory and compositing on a phone even at opacity 0.
  const visibility = useTransform(opacity, (v) => (v <= 0.001 ? "hidden" : "visible"));
  return { opacity, y, visibility };
}

/** Desktop: the scroll-scrubbed frame sequence. */
function HeroScrub({ reducedMotion }: { reducedMotion: boolean }) {
  const containerRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const framesRef = useRef<Array<HTMLImageElement | undefined>>([]);
  const anchorXRef = useRef(ANCHOR_BASE);
  const entered = useHasMounted() || reducedMotion;

  /** Scroll progress through the hero, 0 at the top of the container and 1
   * when its bottom reaches the bottom of the viewport.
   *
   * Driven by the component's own rAF loop below rather than by
   * `useScroll`, and this is the second half of the lag fix. The old chain
   * was: gsap.ticker -> Lenis writes scrollY -> native scroll event ->
   * Framer samples it -> useMotionValueEvent fires -> requestAnimationFrame
   * -> draw. Each arrow is a chance to land in the next frame, and the last
   * one guarantees it, so the athlete was painted at a scroll position the
   * page had already left. On a smooth Lenis scroll that reads exactly like
   * the image lagging behind the page, because it is.
   *
   * Reading the container's own rect inside a rAF collapses all of that:
   * Lenis has already written this frame's scroll position by the time our
   * callback runs (gsap.ticker registers its rAF first, at Lenis init), so
   * the rect is current, and the canvas is drawn from it in the same frame.
   * The beats hang off the same motion value, so type and image can never
   * disagree about where the page is. */
  const progress = useMotionValue(0);

  const segments = useMemo(() => buildTimeline(DESKTOP.chapters), []);

  const pastHeroDisplay = useTransform(progress, (v) => (v >= 1 ? "none" : "block"));
  // The h1 is the `stance` chapter (segments[0]) and leaves the way every
  // other chapter does: held through its dwell, then crossfaded out as the
  // athlete starts to move. It has no fade *in* — it is the first thing on
  // screen, and animates itself in on mount instead (see the render below).
  const introOpacity = useTransform(progress, [segments[0].holdEnd, segments[0].holdEnd + 0.035], [1, 0]);
  const introVisibility = useTransform(introOpacity, (v) => (v <= 0.001 ? "hidden" : "visible"));
  // Picks up exactly where the last beat's fade-out ends (holdEnd + tail),
  // so the blackout continues the dissolve instead of leaving a stretch of
  // bare frame-scrub between "last beat gone" and "next section visible".
  const blackoutOpacity = useTransform(progress, [1 - OUTRO, 1], [0, 1]);

  // Called a fixed 4 times (one per BEATS entry) in the same order every
  // render, same as any other hook — not looped via BEATS.map(), which
  // would make the call count depend on runtime data instead of source
  // order. segments[0] is the opening stance, which has no beat.
  const beat0 = useBeatMotion(progress, segments[1], reducedMotion);
  const beat1 = useBeatMotion(progress, segments[2], reducedMotion);
  const beat2 = useBeatMotion(progress, segments[3], reducedMotion);
  const beat3 = useBeatMotion(progress, segments[4], reducedMotion);
  const beatMotions = [beat0, beat1, beat2, beat3];

  useEffect(() => {
    const set = DESKTOP;
    const canvas = canvasRef.current;
    // alpha:false — every draw fills the whole canvas before blitting the
    // frame, so there is never anything to composite through to the page
    // behind it, and an opaque backing store skips that blend per paint.
    const ctx = canvas?.getContext("2d", { alpha: false });
    const container = containerRef.current;
    if (!canvas || !ctx || !container) return;

    framesRef.current = [];

    /** Match the drawing buffer to the canvas's own rendered CSS box (not
     * window.innerWidth) so it follows whatever width the stylesheet
     * currently gives it — the right-hand wedge the media query on
     * .hero-canvas defines. Deliberately
     * doesn't set canvas.style.width/height: an inline style would outrank
     * that stylesheet rule and pin the box to whichever size was measured
     * first, never picking up a later breakpoint change.
     *
     * Called from the rAF loop rather than from a resize listener, and
     * reports whether it actually resized — assigning canvas.width clears
     * the backing store, so the caller has to know to repaint. Polling the
     * box also covers the cases a resize event misses: the mobile URL bar
     * collapsing, and the CSS box changing at a breakpoint without the
     * window changing size. */
    const syncSize = () => {
      const box = canvas.getBoundingClientRect();
      if (!box.width || !box.height) return false;
      const dpr = Math.min(window.devicePixelRatio || 1, set.maxDpr);
      const w = Math.round(box.width * dpr);
      const h = Math.round(box.height * dpr);
      if (w === canvas.width && h === canvas.height) return false;
      canvas.width = w;
      canvas.height = h;
      return true;
    };
    syncSize();

    /** Cover-fit into the canvas box, anchored horizontally by anchorXRef.
     * The canvas is a tall right-hand wedge, so cropping the 16:9 frame to
     * fill it is the intended composition. */
    const draw = (img: CanvasImageSource, w: number, h: number, cw: number, ch: number) => {
      const scale = Math.max(cw / w, ch / h) * IMAGE_SCALE;
      const dw = w * scale;
      const dh = h * scale;
      ctx.fillStyle = BACKDROP_FALLBACK;
      ctx.fillRect(0, 0, cw, ch);
      ctx.drawImage(img, (cw - dw) * (1 - anchorXRef.current), (ch - dh) / 2, dw, dh);
    };

    const drawFrame = (target: number) => {
      // Scrubbing can outrun the loader. Fall back to the nearest earlier
      // frame that has arrived so the scrub keeps moving instead of
      // freezing on whatever was last painted.
      let index = Math.max(0, Math.min(set.count - 1, target));
      while (index >= 0 && !framesRef.current[index]) index--;
      const img = framesRef.current[index];
      if (!img) return;
      draw(img, img.naturalWidth, img.naturalHeight, canvas.width, canvas.height);
    };
    let cancelled = false;

    /** Decode up front, so no frame is ever decoded for the first time
     * during a scroll.
     *
     * Nothing here used to decode at all: `new Image()` with
     * `decoding = "async"` only permits an off-thread decode, it does not
     * request one, so the first `drawImage` of each frame decoded it
     * synchronously on the main thread — hundreds of first-time decodes
     * landing precisely during the user's first scroll through the hero.
     *
     * HTMLImageElement rather than ImageBitmap: 175 frames at 1280x720 is
     * ~615 MB decoded, far too much to pin as bitmaps. Leaving them as
     * elements lets the browser evict under memory pressure, at the cost of
     * an occasional re-decode — a trade a desktop absorbs and a phone could
     * not, which is one of the reasons mobile plays a video instead. */
    const loadFrame = async (i: number) => {
      if (cancelled || framesRef.current[i]) return;
      try {
        const img = new Image();
        img.decoding = "async";
        img.src = framePath(set.dir, i);
        await img.decode();
        if (cancelled) return;
        framesRef.current[i] = img;
      } catch {
        // A frame that fails to load is skipped, not retried: drawFrame
        // falls back to the nearest earlier frame, so a hole costs a
        // repeated frame rather than a frozen scrub.
      }
    };

    (async () => {
      // Anchors first, in this order: whatever the network is doing, the
      // frames the scrub actually stops on are the ones already decoded, so
      // every hold lands on its sharp photograph rather than on drawFrame's
      // nearest-earlier fallback. The in-between frames only ever flash
      // past.
      await loadFrame(set.chapters[0].frame);
      if (cancelled) return;
      drawFrame(set.chapters[0].frame);
      // Preloader.tsx holds the loader until ".hero-container" exists and
      // this fires; HeroLoop dispatches the same event when its video is
      // ready, so the loader's contract is the same whichever renders.
      window.dispatchEvent(new Event("map:hero-ready"));

      await Promise.all(set.chapters.map((c) => loadFrame(c.frame)));
      if (cancelled) return;

      // Under reduced motion the frame only ever snaps between anchors, so
      // pulling the rest would be the entire sequence downloaded to be
      // never shown.
      if (reducedMotion) return;

      let next = 0;
      await Promise.all(
        Array.from({ length: LOAD_CONCURRENCY }, async () => {
          while (!cancelled && next < set.count) await loadFrame(next++);
        }),
      );
    })();

    /** One rAF, reading the container's live rect and painting from it in
     * the same frame — see the note on `progress` above for why this
     * replaces a scroll listener. It also subsumes the old resize handler:
     * a viewport change moves the rect, so the loop re-measures and
     * repaints without a separate listener that could fire out of step
     * with it. */
    let raf = 0;
    let lastDrawn = -1;
    const tick = () => {
      raf = requestAnimationFrame(tick);

      const rect = container.getBoundingClientRect();
      const span = rect.height - window.innerHeight;
      const p = span > 0 ? Math.max(0, Math.min(1, -rect.top / span)) : 0;
      progress.set(p);
      // Past the hero the canvas is display:none, so it has no box to
      // measure and nothing to paint.
      if (p >= 1) return;

      if (syncSize()) lastDrawn = -1;

      const target = reducedMotion
        ? segments[chapterAtProgress(segments, p)].frame
        : Math.round(frameAtProgress(segments, p));

      const anchor = computeAnchorX(p);
      if (target === lastDrawn && Math.abs(anchor - anchorXRef.current) <= 0.001) return;
      anchorXRef.current = anchor;
      lastDrawn = target;
      drawFrame(target);
    };
    raf = requestAnimationFrame(tick);

    return () => {
      cancelled = true;
      cancelAnimationFrame(raf);
      framesRef.current = [];
    };
  }, [reducedMotion, segments, progress]);

  return (
    <div ref={containerRef} className="hero-container is-scrub">
      <motion.canvas ref={canvasRef} className="hero-canvas" style={{ display: pastHeroDisplay }} />

      <motion.div
        className="hero-blackout"
        style={{ opacity: blackoutOpacity, display: pastHeroDisplay }}
        aria-hidden
      />

      {BEATS.map((beat, i) => (
        <motion.div
          key={beat.key}
          className="hero-beat"
          style={{ opacity: beatMotions[i].opacity, visibility: beatMotions[i].visibility }}
        >
          <span className="hero-beat-numeral font-display" aria-hidden>
            {beat.index}
          </span>
          <motion.div className="hero-beat-inner" style={{ y: beatMotions[i].y }}>
            <BeatCopy beat={beat} />
          </motion.div>
        </motion.div>
      ))}

      <motion.div
        className="hero-content"
        style={{ opacity: introOpacity, visibility: introVisibility }}
      >
        {/* One headline, one message — "Limit" is the only accent color in
            the whole hero, so it actually reads as emphasis instead of
            competing with a separate overline + tagline saying similar
            things in three different places. */}
        <HeroHeadline entered={entered} reducedMotion={reducedMotion} />
      </motion.div>

      <div className="hero-scroll-spacer" aria-hidden />
    </div>
  );
}

// ---------------------------------------------------------------------------
// Mobile
// ---------------------------------------------------------------------------

/** Opacity and lift for one beat, windowed on its pass of the video. Same
 * shape as useBeatMotion, driven by the clip's clock instead of the
 * scrollbar. */
function useLoopBeat(phase: MotionValue<number>, window: LoopWindow, reducedMotion: boolean) {
  const f = LOOP_FADE;
  // The first window starts at the cycle's own origin, so it has nothing
  // before it to fade across — it rises from zero as the cycle restarts.
  // That leaves a fraction of a second at the wrap with the copy at its
  // dimmest, which is deliberate: it lands on the frame where the footage
  // cuts, so the two read as one change rather than as a gap.
  const inFrom = window.from === 0 ? 0 : window.from - f;
  const inTo = window.from === 0 ? f * 2 : window.from + f;
  const opacity = useTransform(phase, [inFrom, inTo, window.to - f, window.to + f], [0, 1, 1, 0]);
  const rawY = useTransform(phase, [inFrom, inTo], [26, 0]);
  const y = useTransform(rawY, (v) => (reducedMotion ? 0 : v));
  const visibility = useTransform(opacity, (v) => (v <= 0.001 ? "hidden" : "visible"));
  return { opacity, y, visibility };
}

/** Mobile: the clip on a loop, with the copy advancing one beat per pass.
 *
 * Nothing here is scroll-linked. The hero is one ordinary viewport-tall
 * section, so scrolling past it is just scrolling, and the moving image
 * costs the main thread nothing — decoding and compositing a video is the
 * one job a phone does entirely in hardware. */
function HeroLoop({ reducedMotion }: { reducedMotion: boolean }) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const entered = useHasMounted() || reducedMotion;
  const phase = useMotionValue(0);
  const windows = useMemo(() => buildLoopWindows(MOBILE.chapters), []);

  const beat0 = useLoopBeat(phase, windows[1], reducedMotion);
  const beat1 = useLoopBeat(phase, windows[2], reducedMotion);
  const beat2 = useLoopBeat(phase, windows[3], reducedMotion);
  const beat3 = useLoopBeat(phase, windows[4], reducedMotion);
  const beatMotions = [beat0, beat1, beat2, beat3];

  // The h1 holds the loop's first window and leaves the way the beats do.
  const introOpacity = useTransform(
    phase,
    [windows[0].to - LOOP_FADE, windows[0].to + LOOP_FADE],
    [1, 0],
  );
  const introVisibility = useTransform(introOpacity, (v) => (v <= 0.001 ? "hidden" : "visible"));

  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;

    // Set on the element as well as in JSX: `muted` is the condition every
    // browser puts on inline autoplay, and React has historically not
    // reflected it to the attribute in time for the first play attempt.
    video.muted = true;
    video.defaultMuted = true;

    // playbackRate is reset by a load, so it is reapplied on every
    // loadedmetadata rather than set once.
    const applyRate = () => {
      video.playbackRate = reducedMotion ? 1 : LOOP_RATE;
    };
    applyRate();
    video.addEventListener("loadedmetadata", applyRate);

    let announced = false;
    const announce = () => {
      if (announced) return;
      announced = true;
      window.dispatchEvent(new Event("map:hero-ready"));
    };
    video.addEventListener("loadeddata", announce);
    // Announce regardless if the video never gets there, so a phone that
    // refuses to load it does not sit behind the preloader.
    const fallbackReady = window.setTimeout(announce, 4000);
    if (video.readyState >= 2) announce();

    if (!reducedMotion) {
      // iOS Low Power Mode refuses inline autoplay even when muted. There
      // is nothing to do about that except not depend on it: the poster
      // stays up, and the clock below keeps the copy cycling, so the hero
      // still reads as a hero rather than a frozen image with one line on
      // it.
      void video.play().catch(() => {});
    }

    /** The cycle's clock: which pass of the video we are on, plus how far
     * through it — so `phase` runs 0..1 across all five passes, one beat
     * per pass.
     *
     * Counted off the video rather than off a timer so the copy advances in
     * the same instant the footage cuts, every time, with no drift to
     * accumulate over a visit. A pass is over when currentTime goes
     * backwards; the tolerance is there because a looping video reports a
     * currentTime that can jitter by a frame either way around the wrap,
     * and a bare `t < last` would count some of those as extra passes.
     *
     * Wall time takes over when the video is not actually playing (iOS Low
     * Power Mode, a backgrounded tab, reduced motion holding the poster) so
     * the copy still cycles over the poster rather than stranding whichever
     * beat happened to be up. */
    const passes = MOBILE.chapters.length;
    const started = performance.now();
    const cycleMs = ((video.duration || 8) * 1000 * passes) / (reducedMotion ? 1 : LOOP_RATE);
    let pass = 0;
    let lastTime = 0;
    let raf = 0;
    const tick = () => {
      raf = requestAnimationFrame(tick);
      if (!reducedMotion && !video.paused && video.duration > 0) {
        const t = video.currentTime;
        if (t < lastTime - 0.1) pass = (pass + 1) % passes;
        lastTime = t;
        phase.set((pass + t / video.duration) / passes);
        return;
      }
      phase.set(((performance.now() - started) / cycleMs) % 1);
    };
    raf = requestAnimationFrame(tick);

    return () => {
      cancelAnimationFrame(raf);
      window.clearTimeout(fallbackReady);
      video.removeEventListener("loadedmetadata", applyRate);
      video.removeEventListener("loadeddata", announce);
    };
  }, [reducedMotion, phase]);

  const crop = MOBILE.crop;
  const plate = MOBILE.plate;

  return (
    <div
      className="hero-container is-loop"
      style={
        {
          "--hero-diagonal-left": `${MOBILE_DIAGONAL_LEFT * 100}%`,
          "--hero-diagonal-right": `${MOBILE_DIAGONAL_RIGHT * 100}%`,
          // The band the athlete stands in, reproducing in CSS exactly what
          // the desktop canvas does in drawImage: size him off the viewport
          // width, cap that against viewport height so he stays clear of the
          // diagonal (MOBILE_MAX_HEIGHT), and stand his feet on
          // MOBILE_FEET_Y rather than centring the band — which is what
          // keeps the floor line still while his pose changes on top of it.
          "--band-h": `min(${(100 * crop.height) / crop.width}vw, ${MOBILE_MAX_HEIGHT * 100}vh)`,
          "--band-w": `calc(var(--band-h) * ${crop.width / crop.height})`,
          "--band-top": `calc(${MOBILE_FEET_Y * 100}% - ${MOBILE.groundY} * var(--band-h))`,
          // The video is the *uncropped* clip, so it is wider than the band
          // and overflows it on both sides — that overflow is the crop. The
          // nudge re-centres it on the crop's own centre rather than the
          // frame's, the 4px that made the difference between him being
          // centred on a phone and sitting slightly left of it.
          "--video-w": `calc(var(--band-h) * ${crop.source.width / crop.source.height})`,
          "--video-dx": `calc(var(--video-w) * ${
            (crop.source.width / 2 - (crop.left + crop.width / 2)) / crop.source.width
          })`,
          "--plate-top": plate[0],
          "--plate-bottom": plate[1],
        } as React.CSSProperties
      }
    >
      <div className="hero-loop-plate" aria-hidden>
        <div className="hero-loop-band">
          <video
            ref={videoRef}
            className="hero-video"
            src={HERO_VIDEO}
            poster={MOBILE.posterSrc}
            preload="auto"
            loop
            muted
            playsInline
            autoPlay={!reducedMotion}
            disablePictureInPicture
            tabIndex={-1}
          />
        </div>
      </div>

      {BEATS.map((beat, i) => (
        <motion.div
          key={beat.key}
          className="hero-beat"
          style={{ opacity: beatMotions[i].opacity, visibility: beatMotions[i].visibility }}
        >
          <span className="hero-beat-numeral font-display" aria-hidden>
            {beat.index}
          </span>
          <motion.div className="hero-beat-inner" style={{ y: beatMotions[i].y }}>
            <BeatCopy beat={beat} />
          </motion.div>
        </motion.div>
      ))}

      <motion.div
        className="hero-content"
        style={{ opacity: introOpacity, visibility: introVisibility }}
      >
        <HeroHeadline entered={entered} reducedMotion={reducedMotion} />
      </motion.div>
    </div>
  );
}

// ---------------------------------------------------------------------------

export function EquipmentHeroSection() {
  const reducedMotion = useReducedMotion();

  /** Which rendering to mount. Deliberately null until after mount and
   * resolved from matchMedia rather than from a render-time hook: a hook
   * that server-renders as `false` would have every phone start pulling the
   * desktop frame set during hydration before correcting itself, and a
   * laptop start fetching the video. Nothing loads until this is known.
   *
   * The two are separate components rather than one with a branch inside,
   * so crossing the breakpoint unmounts the whole of the previous one —
   * there is no path where a video keeps decoding behind a canvas, or a
   * scroll loop keeps measuring a container that is now one viewport tall. */
  const [variant, setVariant] = useState<Variant | null>(null);

  useEffect(() => {
    const mql = window.matchMedia(`(max-width: ${MOBILE_BREAKPOINT}px)`);
    const apply = () => setVariant(mql.matches ? "mobile" : "desktop");
    apply();
    mql.addEventListener("change", apply);
    return () => mql.removeEventListener("change", apply);
  }, []);

  // Server-rendered, and on screen for the one frame before matchMedia
  // resolves: the container and its spacer, nothing that loads. It carries
  // the height the real hero will have — six viewports on a laptop, one on
  // a phone, decided by the stylesheet at the same breakpoint — so the page
  // below it does not jump when the rendering swaps in. Preloader.tsx finds
  // .hero-container here too, which is why it keys on that rather than on
  // anything inside.
  if (!variant) {
    return (
      <div className="hero-container is-pending">
        <div className="hero-scroll-spacer" aria-hidden />
      </div>
    );
  }
  return variant === "mobile" ? (
    <HeroLoop reducedMotion={reducedMotion} />
  ) : (
    <HeroScrub reducedMotion={reducedMotion} />
  );
}
