"use client";

import { useEffect, useRef, useState } from "react";
import { motion, useScroll, useTransform, useMotionValueEvent, type MotionValue } from "framer-motion";
import { RECOVERY_FEATURES, COMMUNITY_BANNER, TRAINING_MODALITIES } from "@/lib/constants";
import { useReducedMotion } from "@/lib/useReducedMotion";
import { useHasMounted } from "@/lib/useHasMounted";
import desktopManifest from "@/public/hero/desktop/manifest.json";
import mobileManifest from "@/public/hero/mobile/manifest.json";
import "./equipment-hero-section.css";

/** Both frame sets are generated by scripts/encode-hero-frames.mjs from the
 * PNG masters in public/athlete/ — see that file for why the masters can't
 * be served directly (226 MB, ~1.76 GB decoded, fully-opaque alpha, and PNG
 * decode costs that mobile Safari cannot absorb at scroll rate).
 *
 * Mobile is not just a smaller desktop: its frames are pre-cropped to the
 * window the athlete actually occupies. A phone viewport is portrait, so
 * cover-fitting the full 16:9 master showed only its centre ~26% of width
 * and sliced the legs off the run and dive frames — which is why mobile
 * never looked like the desktop composition. */
type FrameSet = {
  dir: string;
  count: number;
  width: number;
  height: number;
  /** Fraction of the frame's height where his feet meet the floor. */
  groundY: number;
  /** Per-frame [above, below] fill colours, mobile only. */
  backdrops?: readonly (readonly string[])[];
  /** Device-pixel-ratio ceiling for the drawing buffer. */
  maxDpr: number;
};

const FRAME_SETS: Record<Variant, FrameSet> = {
  desktop: { dir: "/hero/desktop", ...desktopManifest, maxDpr: 2 },
  // 1.5 rather than 2: the mobile frames are 528px wide and a phone's CSS
  // viewport is ~390px, so 1.5 already samples them essentially 1:1 (585px).
  // Going to 2 would ask for 780px out of a 528px source — pure upscale —
  // while nearly doubling the fill-and-blit cost of every drawn frame.
  mobile: { dir: "/hero/mobile", ...mobileManifest, maxDpr: 1.5 },
};

type Variant = "desktop" | "mobile";

const framePath = (set: FrameSet, i: number) =>
  `${set.dir}/${String(i).padStart(4, "0")}.webp`;

const IMAGE_SCALE = 1;
// Matches the .hero-canvas media query breakpoint (max-width: 768px) in
// equipment-hero-section.css.
const MOBILE_BREAKPOINT = 768;

/** The mobile diagonal, as fractions of viewport height where the split
 * meets the left and right edges of the screen. Everything above it is
 * clipped off the canvas, exposing the container's midnight background, so
 * the hero reads as a black field over a red one — the portrait answer to
 * the desktop wedge. These are handed to the stylesheet as custom
 * properties on .hero-container (see the render below) rather than written
 * twice, because MOBILE_MAX_HEIGHT below is derived from them. */
const MOBILE_DIAGONAL_LEFT = 0.62;
const MOBILE_DIAGONAL_RIGHT = 0.28;

/** Where the athlete's feet land, as a fraction of viewport height, and the
 * most of the viewport height his band may occupy. Anchoring to his feet
 * rather than centring the band keeps him standing at the same height on
 * screen across every viewport, and keeps the floor line stable while his
 * pose changes underneath it.
 *
 * MOBILE_MAX_HEIGHT is not a round number: it is the largest cap that keeps
 * every frame's silhouette clear of the diagonal above. The band is sized
 * off the canvas *width*, while the diagonal is placed off its *height*, so
 * on a short wide viewport he grows relative to the split and his head
 * crosses it — at the old 0.92 he was cut on every 16:9 phone. Capping the
 * band against viewport height instead shrinks him there (the backdrop fill
 * takes the spare width) and leaves modern ~19.5:9 phones, where width
 * still binds, untouched.
 *
 * Verify with `node scripts/verify-hero-diagonal.mjs` after changing any of
 * these, the diagonal, or the crop — it measures the published frames. */
const MOBILE_FEET_Y = 0.88;
const MOBILE_MAX_HEIGHT = 0.425;

// Horizontal anchor for drawImage's cover-fit crop: 0 = left edge of the
// frame shown, 0.5 = centered, 1 = right edge. Desktop only — the canvas is
// confined to a right-hand column there (see the CSS media query on
// .hero-canvas), so this only needs to add a small further nudge, drifted
// toward as the user scrolls so the athlete visibly settles rightward
// rather than sitting static. Mobile does not cover-fit at all (see
// drawMobile), so it has no anchor.
const ANCHOR_DESKTOP_BASE = 0.5;
const ANCHOR_DESKTOP_MAX = 0.64;
const ANCHOR_SCROLL_WINDOW = 0.06;

function computeAnchorX(isMobile: boolean, progress: number) {
  if (isMobile) return ANCHOR_DESKTOP_BASE;
  const t = Math.max(0, Math.min(1, progress / ANCHOR_SCROLL_WINDOW));
  return ANCHOR_DESKTOP_BASE + (ANCHOR_DESKTOP_MAX - ANCHOR_DESKTOP_BASE) * t;
}

/** How many frames may be in flight at once behind the first one. The
 * previous code queued every remaining frame in a single synchronous loop,
 * which on a phone meant hundreds of simultaneous requests contending with
 * each other and with the fonts and the rest of the page. Loading in
 * ascending order with a small window instead means the frames the scrub
 * reaches first are the ones that arrive first. */
const LOAD_CONCURRENCY = 6;

type Side = "left" | "right";

// `heading` must contain `accent` verbatim once — the render below splits
// on it to color that one word, the same "single accent word" rule
// .hero-headline follows for "Limit".
const BEATS: Array<{
  index: string;
  label: string;
  heading: string;
  accent: string;
  body: string;
  side: Side;
  enter: number;
  leave: number;
}> = [
  {
    index: "01",
    label: "Move",
    heading: "Train Like An Athlete.",
    accent: "Athlete",
    body: TRAINING_MODALITIES.slice(0, 4)
      .map((m) => m.title)
      .join(". ") + ".",
    side: "left",
    enter: 0.24,
    leave: 0.4,
  },
  {
    index: "02",
    label: "Recover",
    heading: "Recover Like A Pro.",
    accent: "Recover",
    body: RECOVERY_FEATURES.map((f) => f.title).join(". ") + ".",
    // `side` only picks the slide-in direction (useBeatMotion) — every beat
    // still *settles* in the left column (all three render
    // .hero-beat.align-left below; the athlete's wedge on the right is his
    // alone, never text).
    side: "right",
    enter: 0.49,
    leave: 0.64,
  },
  {
    index: "03",
    label: "Belong",
    heading: "This Is MAP.",
    accent: "MAP",
    body: COMMUNITY_BANNER,
    side: "left",
    enter: 0.73,
    leave: 0.89,
  },
];

/** Opacity fades in/out across [enter, leave]; x slides in from `side` only
 * during the enter fade, then holds at 0 — same enter/leave-window pattern
 * Royal Pop drives its per-section text with, expressed as Framer Motion
 * transforms instead of a manual onUpdate/GSAP timeline so it matches how
 * the rest of this hero (and the mountain hero it replaced) already reads
 * scroll: everything off one scrollYProgress motion value, no setState.
 *
 * `filter` adds the pause.co.in-style motion-blur-in: each beat starts
 * heavily blurred and resolves to sharp focus over the same enter window
 * the slide plays over (confirmed by diffing their site's settled vs.
 * transitioning frames — the blur is transition-only, gone once a chapter
 * is fully in view), and re-blurs slightly on the way out so the next
 * beat's crossfade reads as one chapter dissolving into the next rather
 * than a hard cut. */
function useBeatMotion(
  scrollYProgress: MotionValue<number>,
  enter: number,
  leave: number,
  side: Side,
  reducedMotion: boolean,
) {
  const fade = 0.04;
  const opacity = useTransform(scrollYProgress, [enter - fade, enter, leave, leave + fade], [0, 1, 1, 0]);
  const rawX = useTransform(scrollYProgress, [enter - fade, enter], [side === "left" ? -70 : 70, 0]);
  const x = useTransform(rawX, (v) => (reducedMotion ? 0 : v));
  const rawBlur = useTransform(
    scrollYProgress,
    [enter - fade, enter, leave, leave + fade],
    [10, 0, 0, 6],
  );
  const filter = useTransform(rawBlur, (v) => `blur(${reducedMotion ? 0 : v}px)`);
  return { opacity, x, filter };
}

export function EquipmentHeroSection() {
  const containerRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const framesRef = useRef<HTMLImageElement[]>([]);
  // Fallback fill behind a desktop frame — matches the athlete sequence's
  // solid red backdrop. With IMAGE_SCALE=1 (true cover) this is only ever
  // visible for a sub-pixel rounding edge. Mobile never uses it: it fills
  // from the per-frame sampled colours in the manifest instead.
  const bgColorRef = useRef("#c21300");
  const currentFrameRef = useRef(-1);
  // Set inside the mount effect below (it closes over the canvas/ctx sized
  // there); the scroll handler calls through this ref instead of
  // duplicating the draw logic or re-creating the effect per scroll tick.
  const drawFrameRef = useRef<() => void>(() => {});
  const rafRef = useRef(0);
  // Horizontal cover-fit anchor (see computeAnchorX) plus the inputs needed
  // to recompute it outside the scroll handler — on resize (a breakpoint
  // crossing changes isMobile) and read back when a resize fires with no
  // scroll change in between.
  const anchorXRef = useRef(ANCHOR_DESKTOP_BASE);
  const lastProgressRef = useRef(0);
  const reducedMotion = useReducedMotion();

  /** Which frame set to load. Deliberately null until after mount and
   * resolved from matchMedia rather than from a render-time hook: a hook
   * that server-renders as `false` would have every phone start pulling the
   * desktop set during hydration before correcting itself. Nothing loads
   * until this is known. */
  const [variant, setVariant] = useState<Variant | null>(null);

  useEffect(() => {
    const mql = window.matchMedia(`(max-width: ${MOBILE_BREAKPOINT}px)`);
    const apply = () => setVariant(mql.matches ? "mobile" : "desktop");
    apply();
    mql.addEventListener("change", apply);
    return () => mql.removeEventListener("change", apply);
  }, []);

  // Framer Motion server-renders using the `animate` values, not `initial`
  // (so no-JS/slow-hydration users see the correct final layout rather than
  // hidden/offset text) — then, on hydrate, if the DOM already matches
  // `animate`, it skips the enter transition entirely rather than replaying
  // it. That made every "slide in" here a no-op: the SSR HTML already had
  // opacity:1/transform:none baked in, so hydration had nothing to animate
  // toward. Gating `animate` on a state flip that only happens client-side,
  // after mount, forces a genuine post-mount prop change, which Framer
  // Motion always animates regardless of what SSR produced.
  const mounted = useHasMounted();
  const entered = mounted || reducedMotion;

  // Same imperative, no-setState scroll pattern as the mountain hero this
  // replaces (see horizon-hero-section.tsx) — a scroll-linked motion value
  // read via useMotionValueEvent, never React state, so frame changes never
  // trigger a re-render.
  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start start", "end end"],
  });
  const pastHeroDisplay = useTransform(scrollYProgress, (v) => (v >= 1 ? "none" : "block"));
  // Starts the instant beat 3 finishes fading out (enter/leave above put
  // that at progress ~0.93) so the blackout picks up where the last beat's
  // own fade-out left off, rather than leaving a silent stretch of plain
  // frame-scrub in between — that gap was the dead black space before this
  // was tuned.
  const blackoutOpacity = useTransform(scrollYProgress, [0.93, 1], [0, 1]);

  // Called a fixed 3 times (one per BEATS entry) in the same order every
  // render, same as any other hook — not looped via BEATS.map(), which
  // would make the call count depend on runtime data instead of source order.
  const beat0 = useBeatMotion(scrollYProgress, BEATS[0].enter, BEATS[0].leave, BEATS[0].side, reducedMotion);
  const beat1 = useBeatMotion(scrollYProgress, BEATS[1].enter, BEATS[1].leave, BEATS[1].side, reducedMotion);
  const beat2 = useBeatMotion(scrollYProgress, BEATS[2].enter, BEATS[2].leave, BEATS[2].side, reducedMotion);
  const beatMotions = [beat0, beat1, beat2];

  useEffect(() => {
    if (!variant) return;
    const set = FRAME_SETS[variant];
    const isMobile = variant === "mobile";
    const canvas = canvasRef.current;
    // alpha:false — every draw fills the whole canvas before blitting the
    // frame, so there is never anything to composite through to the page
    // behind it, and an opaque backing store skips that blend per paint.
    const ctx = canvas?.getContext("2d", { alpha: false });
    if (!canvas || !ctx) return;

    // Frames from the other variant are the wrong crop and the wrong size,
    // so a breakpoint crossing starts over rather than drawing them scaled.
    framesRef.current = [];
    currentFrameRef.current = -1;

    // Sized from the canvas's own rendered CSS box (not window.innerWidth)
    // so the drawing buffer follows whatever width the stylesheet currently
    // gives it — full-bleed on mobile, confined to the right-hand column on
    // desktop (see the media query on .hero-canvas). Deliberately doesn't
    // set canvas.style.width/height: an inline style would outrank that
    // stylesheet rule and pin the box to whichever size was measured first,
    // never picking up a later breakpoint change.
    const sizeCanvas = () => {
      const dpr = Math.min(window.devicePixelRatio || 1, set.maxDpr);
      const rect = canvas.getBoundingClientRect();
      const cssWidth = rect.width || window.innerWidth;
      const cssHeight = rect.height || window.innerHeight;
      canvas.width = Math.round(cssWidth * dpr);
      canvas.height = Math.round(cssHeight * dpr);
    };
    sizeCanvas();
    anchorXRef.current = computeAnchorX(isMobile, lastProgressRef.current);

    /** Cover-fit into the canvas box, anchored horizontally by anchorXRef.
     * The desktop canvas is a tall right-hand wedge, so cropping the 16:9
     * frame to fill it is the intended composition. */
    const drawDesktop = (img: HTMLImageElement, cw: number, ch: number) => {
      const scale = Math.max(cw / img.naturalWidth, ch / img.naturalHeight) * IMAGE_SCALE;
      const dw = img.naturalWidth * scale;
      const dh = img.naturalHeight * scale;
      ctx.fillStyle = bgColorRef.current;
      ctx.fillRect(0, 0, cw, ch);
      ctx.drawImage(img, (cw - dw) * (1 - anchorXRef.current), (ch - dh) / 2, dw, dh);
    };

    /** Fit the pre-cropped frame to the canvas width (height-capped so he
     * stays clear of the diagonal — see MOBILE_MAX_HEIGHT), stand him on
     * MOBILE_FEET_Y, and fill everything around him with that frame's own
     * backdrop colours. The stylesheet then clips the whole canvas along
     * the diagonal, so this fill only ever shows below the split.
     *
     * Contain-and-fill rather than cover-fit because cover-fitting a
     * landscape plate into a portrait viewport necessarily throws away most
     * of its width — that is what was clipping the run and dive poses. The
     * fill is invisible because the plate is a flat red cyclorama: the
     * manifest carries the mean backdrop colour of each frame's own top and
     * bottom edge rows, drawn as a vertical gradient that canvas clamps to
     * its end colours beyond the band, so the seam step is under 1/255
     * where the film grain itself varies by ~6. */
    const drawMobile = (img: HTMLImageElement, cw: number, ch: number, index: number) => {
      const iw = img.naturalWidth;
      const ih = img.naturalHeight;
      const scale = Math.min(cw / iw, (ch * MOBILE_MAX_HEIGHT) / ih);
      const dw = iw * scale;
      const dh = ih * scale;
      const dy = ch * MOBILE_FEET_Y - dh * set.groundY;

      const backdrop = set.backdrops?.[index];
      if (backdrop) {
        const gradient = ctx.createLinearGradient(0, dy, 0, dy + dh);
        gradient.addColorStop(0, backdrop[0]);
        gradient.addColorStop(1, backdrop[1]);
        ctx.fillStyle = gradient;
      } else {
        ctx.fillStyle = bgColorRef.current;
      }
      ctx.fillRect(0, 0, cw, ch);
      ctx.drawImage(img, (cw - dw) / 2, dy, dw, dh);
    };

    const drawFrame = () => {
      const target = Math.max(0, currentFrameRef.current);
      // Scrubbing can outrun the loader. Fall back to the nearest earlier
      // frame that has arrived so the scrub keeps moving instead of
      // freezing on whatever was last painted.
      let index = target;
      while (index >= 0 && !framesRef.current[index]) index--;
      const img = framesRef.current[index];
      if (!img) return;
      if (isMobile) drawMobile(img, canvas.width, canvas.height, index);
      else drawDesktop(img, canvas.width, canvas.height);
    };
    drawFrameRef.current = drawFrame;

    let cancelled = false;
    const loadFrame = (i: number) =>
      new Promise<void>((resolve) => {
        const img = new Image();
        img.decoding = "async";
        img.onload = () => {
          // Guard on `cancelled`, not just at the call site: when the
          // breakpoint is crossed mid-load (a phone rotating past 768px),
          // the previous variant's requests are still in flight and would
          // otherwise land in the array the new variant just reset —
          // putting a full-frame desktop image into the mobile set, which
          // draws with the wrong crop and geometry.
          if (cancelled) return resolve();
          framesRef.current[i] = img;
          resolve();
        };
        img.onerror = () => resolve();
        img.src = framePath(set, i);
      });

    (async () => {
      // First frame blocks paint and fires readiness; the rest stream in
      // behind it. Preloader.tsx waits on both ".hero-canvas" existing and
      // this "map:hero-ready" event — the same contract the old Three.js
      // hero used, so Preloader needs no changes.
      await loadFrame(0);
      if (cancelled) return;
      currentFrameRef.current = 0;
      drawFrame();
      window.dispatchEvent(new Event("map:hero-ready"));

      // Under reduced motion the scroll handler never advances the frame,
      // so frame 0 is the only one that will ever be painted — pulling the
      // rest would be the entire sequence downloaded to be never shown.
      if (reducedMotion) return;

      let next = 1;
      await Promise.all(
        Array.from({ length: LOAD_CONCURRENCY }, async () => {
          while (!cancelled && next < set.count) await loadFrame(next++);
        }),
      );
    })();

    const onResize = () => {
      sizeCanvas();
      anchorXRef.current = computeAnchorX(isMobile, lastProgressRef.current);
      drawFrame();
    };
    window.addEventListener("resize", onResize);
    return () => {
      cancelled = true;
      window.removeEventListener("resize", onResize);
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
      rafRef.current = 0;
    };
  }, [variant, reducedMotion]);

  useMotionValueEvent(scrollYProgress, "change", (progress) => {
    // Reduced motion: hold whatever frame is currently painted, matching
    // the old hero's rule of skipping scroll-linked camera movement.
    if (reducedMotion || !variant) return;
    const set = FRAME_SETS[variant];
    lastProgressRef.current = progress;
    const index = Math.min(Math.floor(progress * set.count), set.count - 1);
    const nextAnchor = computeAnchorX(variant === "mobile", progress);
    const anchorChanged = Math.abs(nextAnchor - anchorXRef.current) > 0.001;
    if (index === currentFrameRef.current && !anchorChanged) return;
    currentFrameRef.current = index;
    anchorXRef.current = nextAnchor;
    // Coalesce to one paint per frame. Scroll events fire faster than the
    // compositor on a touch flick, and the previous code drew synchronously
    // inside every one of them — so a single flick queued hundreds of
    // full-canvas fills and blits that the display could never show.
    if (rafRef.current) return;
    rafRef.current = requestAnimationFrame(() => {
      rafRef.current = 0;
      drawFrameRef.current();
    });
  });

  return (
    <div
      ref={containerRef}
      className="hero-container"
      style={
        {
          "--hero-diagonal-left": `${MOBILE_DIAGONAL_LEFT * 100}%`,
          "--hero-diagonal-right": `${MOBILE_DIAGONAL_RIGHT * 100}%`,
        } as React.CSSProperties
      }
    >
      <motion.canvas ref={canvasRef} className="hero-canvas" style={{ display: pastHeroDisplay }} />

      <motion.div
        className="hero-blackout"
        style={{ opacity: blackoutOpacity, display: pastHeroDisplay }}
        aria-hidden
      />

      {BEATS.map((beat, i) => (
        <motion.div
          key={beat.index}
          className="hero-beat align-left"
          style={{ opacity: beatMotions[i].opacity }}
        >
          <span className="hero-beat-numeral font-display" aria-hidden>
            {beat.index}
          </span>
          <motion.div
            className="hero-beat-inner"
            style={{ x: beatMotions[i].x, filter: beatMotions[i].filter }}
          >
            <span className="section-label font-display">
              {beat.index} / {beat.label}
            </span>
            <h2 className="beat-heading font-display">
              {beat.heading.split(beat.accent).map((part, j, parts) => (
                <span key={j}>
                  {part}
                  {j < parts.length - 1 && <span className="hero-headline-accent">{beat.accent}</span>}
                </span>
              ))}
            </h2>
            <p className="beat-body">{beat.body}</p>
          </motion.div>
        </motion.div>
      ))}

      <div className="hero-content">
        {/* One headline, one message — "Limit" is the only accent color in
            the whole hero, so it actually reads as emphasis instead of
            competing with a separate overline + tagline saying similar
            things in three different places. */}
        <h1 className="hero-headline">
          <motion.span
            style={{ display: "inline-block", marginRight: "0.28em" }}
            initial={{ opacity: 0, x: -80, filter: "blur(12px)" }}
            animate={
              entered
                ? { opacity: 1, x: 0, filter: "blur(0px)" }
                : { opacity: 0, x: -80, filter: "blur(12px)" }
            }
            transition={{ duration: reducedMotion ? 0 : 0.9, ease: [0.22, 1, 0.36, 1], delay: reducedMotion ? 0 : 0.15 }}
          >
            Your
          </motion.span>
          <motion.span
            className="hero-headline-accent"
            style={{ display: "inline-block", marginRight: "0.28em" }}
            initial={{ opacity: 0, x: 80, filter: "blur(12px)" }}
            animate={
              entered
                ? { opacity: 1, x: 0, filter: "blur(0px)" }
                : { opacity: 0, x: 80, filter: "blur(12px)" }
            }
            transition={{ duration: reducedMotion ? 0 : 0.9, ease: [0.22, 1, 0.36, 1], delay: reducedMotion ? 0 : 0.3 }}
          >
            Limit
          </motion.span>
          <motion.span
            style={{ display: "inline-block" }}
            initial={{ opacity: 0, y: 24, filter: "blur(10px)" }}
            animate={
              entered
                ? { opacity: 1, y: 0, filter: "blur(0px)" }
                : { opacity: 0, y: 24, filter: "blur(10px)" }
            }
            transition={{ duration: reducedMotion ? 0 : 0.9, ease: [0.22, 1, 0.36, 1], delay: reducedMotion ? 0 : 0.45 }}
          >
            Is You.
          </motion.span>
        </h1>
      </div>

      <div className="hero-scroll-spacer" aria-hidden />
    </div>
  );
}
